#!/usr/bin/env python3
"""
register_project — idempotent, BOM-free project registration for ilk-launcher.

Adds a ``{name, path}`` entry to the launcher's ``projects.json`` registry.
The same registry is consumed by:

- ``status_all.py`` (reads as plain utf-8 — BOM breaks it)
- ``scheduler_scan.resolve_repo_path`` (reads with utf-8-sig, BOM-tolerant)

Usage as a library::

    from register_project import register_project
    result = register_project("/path/to/repo")

Usage as a CLI::

    python register_project.py --path /path/to/repo [--name myproj] [--projects-json /tmp/test.json]

Stdlib only.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# ── path normalization (mirrors ilk-feedback collect._normalize_path_for_compare)

def _normalize_path(p: str | Path) -> str:
    """Normalize for cross-platform comparison: lowercase, forward slashes."""
    return str(p).replace("\\", "/").lower().rstrip("/")


# ── core logic

def _default_registry_path() -> Path:
    """Resolve the default projects.json path via ilk_paths launcher dir."""
    # Import ilk_paths from sibling directory
    here = Path(__file__).resolve().parent
    if str(here) not in sys.path:
        sys.path.insert(0, str(here))
    from ilk_paths import external_launcher_dir, project_key, find_project_root  # type: ignore

    # We need a project root to derive the key.  Use cwd as start.
    root, _kind = find_project_root(Path.cwd())
    if root is None:
        # Fallback: use the skill-root launcher dir (legacy layout)
        from ilk_paths import skill_root  # type: ignore
        return skill_root() / "ilk-launcher" / "projects.json"
    key = project_key(root)
    return external_launcher_dir(key) / "projects.json"


def register_project(
    repo_path: str | Path,
    *,
    projects_json: str | Path | None = None,
    name: str | None = None,
) -> dict:
    """Idempotently register *repo_path* in the launcher's projects.json.

    Parameters
    ----------
    repo_path:
        Absolute path to the project root. Must exist on disk.
    projects_json:
        Explicit registry file path (for testing). ``None`` uses the
        default launcher registry resolved via ``ilk_paths``.
    name:
        Display name. Defaults to the leaf directory name of *repo_path*.

    Returns
    -------
    dict with keys ``added`` (bool), ``name`` (str), ``path`` (str),
    ``total`` (int).  ``added`` is False when the path already existed
    or the directory doesn't exist on disk.
    """
    repo = Path(repo_path).resolve()
    reason: str | None = None

    # Real-dir guard
    if not repo.is_dir():
        reason = f"Path does not exist: {repo}"

    resolved_name = name or repo.name
    norm = _normalize_path(repo)

    # Resolve registry path
    reg = Path(projects_json) if projects_json else _default_registry_path()

    # Load existing registry (or start fresh)
    entries: list[dict] = []
    if reg.is_file():
        try:
            data = json.loads(reg.read_text(encoding="utf-8"))
            entries = list(data.get("projects", []))
        except (json.JSONDecodeError, OSError):
            entries = []

    # Dedup by normalized path
    for e in entries:
        if _normalize_path(e.get("path", "")) == norm:
            return {"added": False, "name": e.get("name", resolved_name),
                    "path": str(repo), "total": len(entries),
                    "reason": "already registered"}

    if reason:
        return {"added": False, "name": resolved_name, "path": str(repo),
                "total": len(entries), "reason": reason}

    # Append new entry
    entries.append({"name": resolved_name, "path": str(repo)})

    # Write BOM-free utf-8
    out = {"_comment": (
        "Auto-generated by register_project.py. Used by launch.ps1 "
        "-ProjectName/-All, status_all.py, and the scheduler's repo_path "
        "fallback. Being listed here makes a project eligible for "
        "auto-dispatch by a running scheduler."
    ), "projects": entries}
    reg.parent.mkdir(parents=True, exist_ok=True)
    reg.write_text(json.dumps(out, indent=4, ensure_ascii=False) + "\n",
                   encoding="utf-8")

    return {"added": True, "name": resolved_name, "path": str(repo),
            "total": len(entries)}


# ── CLI

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Register a project in the ilk-launcher projects.json registry.")
    ap.add_argument("--path", required=True, help="Absolute path to the project root.")
    ap.add_argument("--name", default=None, help="Display name (default: leaf dir name).")
    ap.add_argument("--projects-json", default=None,
                    help="Explicit registry file (default: auto-resolve via ilk_paths).")
    args = ap.parse_args(argv)

    result = register_project(args.path, projects_json=args.projects_json, name=args.name)
    print(json.dumps(result, ensure_ascii=False))
    return 0 if result.get("added") else 1


if __name__ == "__main__":
    raise SystemExit(main())
